const constants = {
  SCHEMA_ERROR_MESSAGES: {
    ID_REQUIRED: 'ID required.',
    ID_INVALID_DT: 'ID must be UUID.',
    NAME_REQUIRED: 'Name required.',
    NAME_INVALID_DT: 'Name must be string.',
    SEARCH_REQUIRED: 'Search text required.',
    SEARCH_INVALID_DT: 'Search text must be string.',
    SORT_BY_REQUIRED: 'Sort by required.',
    SORT_BY_INVALID_DT: 'Sort by must be string.',
    ORDER_BY_REQUIRED: 'Order by required.',
    ORDER_BY_INVALID_DT: 'Order by must be string.',
    ORDER_BY_TYPE_INV: 'Invalid value for order type.',
    ORDER_REQUIRED: 'Order required.',
    ORDER_INVALID_DT: 'Order must be boolean.',
    PAGE_REQUIRED: 'Page no required.',
    PAGE_INVALID_DT: 'Page no must be number.',
    LIMIT_REQUIRED: 'Limit required.',
    LIMIT_INVALID_DT: 'Limit must be number.',
    TYPE_REQUIRED: 'Type required.',
    TYPE_INVALID_DT: 'Type must be string.',
    TYPE_INV: 'Invalid value for type.',
    PRICE_REQUIRED: 'Price required.',
    PRICE_INVALID_DT: 'Price must be number.',
    EMAIL_REQUIRED: 'Email required.',
    EMAIL_INVALID_DT: 'Email must be string.',
    TITLE_REQUIRED: 'Title required.',
    TITLE_INVALID_DT: 'Title must be string.',
    CATEGORY_REQUIRED: 'Category required.',
    CATEGORY_INVALID_DT: 'Category must be string.',
    CONTENT_REQUIRED: 'Content required.',
    CONTENT_INVALID_DT: 'Content must be string.',
    PASSWORD_REQUIRED: 'Password required.',
    PASSWORD_INVALID_DT: 'Password must be string.',
    OLD_PASSWORD_REQUIRED: 'Old password required.',
    OLD_PASSWORD_INVALID_DT: 'Old password must be string.',
    COMMENT_REQUIRED: 'Comment required.',
    COMMENT_INVALID_DT: 'Comment must be string.',
    DEPARTMENT_REQUIRED: 'Department required.',
    DEPARTMENT_INVALID_DT: 'Department must be string.',
    COMMON_REQUIRED: '_ required',
    COMMON_DATE_INVALID: '_ is not a valid date.',
    COMMON_INVALID: '_ is not a valid __.',
    FULL_NAME_REQUIRED: 'Full name required.',
    FULL_NAME_INVALID_DT: 'Full name must be string.',
    USERNAME_REQUIRED: 'username required.',
    USERNAME_INVALID_DT: 'username must be string.',
    SURNAME_REQUIRED: 'Surname required.',
    SURNAME_INVALID_DT: 'Surname must be string.',
    PHONE_REQUIRED: 'Phone required.',
    PHONE_INVALID_DT: 'Phone must be number or empty.',
    PHONE_INV: 'Phone number must be more then 8 digit and numbers only.',
    IS_ARCHIVED_REQUIRED: 'Is archived required.',
    IS_ARCHIVED_INVALID_DT: 'Is archived must be boolean.',
    USER_ID_REQUIRED: 'User ID required.',
    USER_ID_INVALID_DT: 'User ID must be UUID.',
    BLOG_ID_REQUIRED: 'Blog ID required.',
    BLOG_ID_INVALID_DT: 'Blog ID must be UUID.',
    USER_ID_INV: 'Invalid value for user id. It should be either a valid UUID or a null.',
    GROUP_ID_REQUIRED: 'Group ID required.',
    GROUP_ID_INVALID_DT: 'Group ID must be number.',
    CUSTOMER_ID_REQUIRED: 'Customer ID required.',
    CUSTOMER_ID_INVALID_DT: 'Customer ID must be number.',
    RECORD_ID_INVALID_DT: 'Record id must be string.',
    RECORD_ID_REQUIRED: 'Record id required.',
    FILTER_TYPE_REQUIRED: 'Filter type required.',
    FILTER_TYPE_INVALID_DT: 'Filter type must be string.',
    FILTER_TYPE_INV: 'Invalid value for filter type.',
    DATE_FILTER_REQUIRED: 'Date Filter type required.',
    DATE_FILTER_INVALID_DT: 'Date Filter type must be string.',
    DATE_FILTER_INV: 'Invalid value for date filter type.',
    FROM_DATE_INVALID_DT: 'From date must be string',
    FROM_DATE_REQUIRED: 'From date required.',
    TO_DATE_INVALID_DT: 'To date must be string',
    TO_DATE_REQUIRED: 'To date required.',
    FROM_YEAR_REQUIRED: 'From year required.',
    FROM_YEAR_INVALID_DT: 'From year must be number.',
    TO_YEAR_REQUIRED: 'To year required.',
    TO_YEAR_INVALID_DT: 'To year must be number.',
    FILTER_YEAR: 'From and To both years are required.',
    YEAR_INV: 'Invalid year.',
    DATE_INV: 'Invalid formate. Valid formate is "yyyy-mm-dd"',
    ROLE_ID_REQUIRED: 'Role ID required.',
    ROLE_ID_INVALID_DT: 'Role ID must be string.',
    RESET_HASH_REQUIRED: 'Reset hash required.',
    RESET_HASH_INVALID_DT: 'Reset hash must be string.',
  },
  ENUMS: {
    ORDER: {
      ASC: 'asc',
      DESC: 'desc',
    },
    DATE_FILTER: {
      ALL_YEAR: 'all year',
      THIS_YEAR: 'this year',
      THIS_MONTH: 'this month',
      THIS_WEEK: 'this week',
      THIS_DAY: 'this day',
      CUSTOM: 'custom',
    },
  },
  RESP_ERR_CODES: {
    ERR_400: 400,
    ERR_401: 401,
    ERR_422: 422,
    ERR_500: 500,
    ERR_404: 404,
    ERR_405: 405,
    ERR_409: 409,
  },
  ERROR_MESSAGES: {
    NOT_AUTHORISED: 'You are not authorized to update this record',
    DELETE_NOT_FOUND: 'Either invalid ID or you are not permitted to perform this action',
    RECORD_NOT_FOUND: 'Not found',
    NOT_PERMITED: 'You are not authorized to perform this operation',
    USER_EXIST: 'User already exists',
    ACCOUNT_EXIST: 'Account already exists',
    ACCOUNT_INVALID: 'Missing or invalid Ad Account.',
    TOKEN_INVALID: 'Missing or invalid auth code.',
    INVALID_RESET_HASH: 'Either invalid hash or invalid user',
    RESET_HASH_EXPIRED: 'Reset token expired',
    INVALID_PASSWORD: 'Invalid password',
    USER_NOT_FOUND: 'User not found',
    INQUIRE_NOT_FOUND: 'Inquire not found',
    BLOG_NOT_FOUND: 'Blog not found',
    BLOG_COMMENT_NOT_FOUND: 'Blog Comment not found',
    IP_NOT_FOUND: 'IP not found',
    PASSWORD_NOT_MATCHED: 'Invalid old password',
    INVALID_USER: 'Invalid old User',
    USER_ALREADY_EXISTS: 'User Already exists',
  },
  EMAIL_SUBJECTS: {
    INVITE_USER: 'Your account has been created',
    RESEND_INVITE_USER: 'You have been invited',
    PASSWORD_RESET: 'Password reset requested',
  },
  TOKEN_EXPIRY: 24.0,
  ADMIN: 'admin',
  SUCCESS_MESSAGES: {
    OK: 'OK',
    PASSWORD_CHANGED: 'Password changed successfully!',
    PASSWORD_RESET: 'Password reset email sent!',
    RESEND_INVITATION: 'Invitation has been sent!',
    SUCCESS_UPDATE: 'Successfully updated!',
    SUCCESS_DELETED: 'Successfully deleted!',
    SUCCESS_REMOVE: 'Successfully removed!',
  },
  NOTIFICATION_TYPES: {
    COMMENT_POST: 'commentPost',
    COMMENT_REPLY: 'commentReply',
    LIKE_POST: 'likePost',
    LIKE_COMMENT: 'likeComment',
  },
};

export default constants;
